"""empty message

Revision ID: 022302295875
Revises: 3719fb5b193a
Create Date: 2018-06-25 19:57:10.783736

"""

# revision identifiers, used by Alembic.
revision = '022302295875'
down_revision = '3719fb5b193a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demo_id', sa.Integer(), nullable=True),
    sa.Column('client_num', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_demo_players_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_demo_players'))
    )
    op.drop_table('match_players')
    with op.batch_alter_table('maps', schema=None) as batch_op:
        batch_op.drop_index('ix_maps_match_id')

    op.drop_table('maps')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maps',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('match_id', sa.INTEGER(), nullable=True),
    sa.Column('map_name', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maps', schema=None) as batch_op:
        batch_op.create_index('ix_maps_match_id', ['match_id'], unique=False)

    op.create_table('match_players',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('gtv_match_id', sa.INTEGER(), nullable=True),
    sa.Column('client_num', sa.INTEGER(), nullable=True),
    sa.Column('player_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('demo_players')
    # ### end Alembic commands ###
