"""empty message

Revision ID: 180e0f82c68c
Revises: 3d584460aeb9
Create Date: 2017-02-27 09:29:43.349630

"""

# revision identifiers, used by Alembic.
revision = '180e0f82c68c'
down_revision = '3d584460aeb9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gtv_match_id', sa.Integer(), nullable=True),
    sa.Column('client_num', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), sa.ForeignKey('players.id'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    #op.create_foreign_key(None, 'renders', 'players', ['player_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'renders', type_='foreignkey')
    op.drop_table('match_players')
    ### end Alembic commands ###
