"""empty message

Revision ID: 1aaa9a9e21dd
Revises: 7b2655d432eb
Create Date: 2020-06-29 20:59:06.497136

"""

# revision identifiers, used by Alembic.
revision = '1aaa9a9e21dd'
down_revision = '7b2655d432eb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(('user_id',), ['users.id'], name=op.f('fk_user_roles_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_roles'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    # ### end Alembic commands ###
