"""empty message

Revision ID: 45aa7927492c
Revises: e361d65f075c
Create Date: 2016-09-14 13:14:40.103768

"""

# revision identifiers, used by Alembic.
revision = '45aa7927492c'
down_revision = 'e361d65f075c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('map_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maps_match_id'), 'maps', ['match_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gamestv_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_gamestv_id'), 'matches', ['gamestv_id'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_gamestv_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_maps_match_id'), table_name='maps')
    op.drop_table('maps')
    ### end Alembic commands ###
