"""empty message

Revision ID: 63abf4a91d17
Revises: 8964d64c28c0
Create Date: 2020-06-30 01:27:19.457601

"""

# revision identifiers, used by Alembic.
revision = '63abf4a91d17'
down_revision = '8964d64c28c0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulletevent',
    sa.Column('dwSeq', sa.Integer(), nullable=False),
    sa.Column('szMd5', sa.String(length=32), nullable=True),
    sa.Column('bRegion', sa.SmallInteger(), nullable=True),
    sa.Column('bTarget', sa.SmallInteger(), nullable=True),
    sa.Column('bAttacker', sa.SmallInteger(), nullable=True),
    sa.Column('dwTime', sa.Integer(), nullable=True),
    sa.Column('bWeapon', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('dwSeq')
    )
    op.create_index(op.f('ix_bulletevent_szMd5'), 'bulletevent', ['szMd5'], unique=False)
    op.create_table('demo',
    sa.Column('dwSeq', sa.Integer(), nullable=False),
    sa.Column('szMd5', sa.String(length=32), nullable=True),
    sa.Column('szName', sa.String(length=64), nullable=True),
    sa.Column('szMapName', sa.String(length=64), nullable=True),
    sa.Column('szPOVName', sa.String(length=64), nullable=True),
    sa.Column('szTeamA', sa.String(length=128), nullable=True),
    sa.Column('szTeamB', sa.String(length=128), nullable=True),
    sa.Column('szServerConfig', sa.Text(), nullable=True),
    sa.Column('dwScanTime', sa.Integer(), nullable=True),
    sa.Column('dwPlayerCount', sa.Integer(), nullable=True),
    sa.Column('dwObitCount', sa.Integer(), nullable=True),
    sa.Column('dwBulletCount', sa.Integer(), nullable=True),
    sa.Column('dwChatCount', sa.Integer(), nullable=True),
    sa.Column('dwFrameCount', sa.Integer(), nullable=True),
    sa.Column('bPOVId', sa.SmallInteger(), nullable=True),
    sa.Column('bIsTVDemo', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('dwSeq')
    )
    op.create_index(op.f('ix_demo_szMd5'), 'demo', ['szMd5'], unique=False)
    op.create_table('obituary',
    sa.Column('dwSeq', sa.Integer(), nullable=False),
    sa.Column('szMd5', sa.String(length=32), nullable=True),
    sa.Column('bAttacker', sa.SmallInteger(), nullable=True),
    sa.Column('bTarget', sa.SmallInteger(), nullable=True),
    sa.Column('bWeapon', sa.SmallInteger(), nullable=True),
    sa.Column('dwTime', sa.Integer(), nullable=True),
    sa.Column('bIsTeamkill', sa.SmallInteger(), nullable=True),
    sa.Column('szTimeString', sa.String(length=32), nullable=True),
    sa.Column('szMessage', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('dwSeq')
    )
    op.create_index(op.f('ix_obituary_szMd5'), 'obituary', ['szMd5'], unique=False)
    op.create_table('player',
    sa.Column('dwSeq', sa.Integer(), nullable=False),
    sa.Column('szMd5', sa.String(length=32), nullable=True),
    sa.Column('szName', sa.String(length=128), nullable=True),
    sa.Column('szCleanName', sa.String(length=64), nullable=True),
    sa.Column('bClientNum', sa.SmallInteger(), nullable=True),
    sa.Column('szInfoString', sa.String(length=128), nullable=True),
    sa.Column('bTeam', sa.SmallInteger(), nullable=True),
    sa.Column('bTVClient', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('dwSeq')
    )
    op.create_index(op.f('ix_player_szMd5'), 'player', ['szMd5'], unique=False)
    op.create_table('revive',
    sa.Column('dwSeq', sa.Integer(), nullable=False),
    sa.Column('szMd5', sa.String(length=32), nullable=True),
    sa.Column('bRevived', sa.SmallInteger(), nullable=True),
    sa.Column('bReviver', sa.SmallInteger(), nullable=True),
    sa.Column('dwTime', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('dwSeq')
    )
    op.create_index(op.f('ix_revive_szMd5'), 'revive', ['szMd5'], unique=False)
    op.create_table('roundstats',
    sa.Column('dwSeq', sa.Integer(), nullable=False),
    sa.Column('szMd5', sa.String(length=32), nullable=True),
    sa.Column('bRound', sa.String(length=128), nullable=True),
    sa.Column('szTimeToBeat', sa.String(length=32), nullable=True),
    sa.Column('dwStartTime', sa.Integer(), nullable=True),
    sa.Column('szStats', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('dwSeq')
    )
    op.create_index(op.f('ix_roundstats_szMd5'), 'roundstats', ['szMd5'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roundstats_szMd5'), table_name='roundstats')
    op.drop_table('roundstats')
    op.drop_index(op.f('ix_revive_szMd5'), table_name='revive')
    op.drop_table('revive')
    op.drop_index(op.f('ix_player_szMd5'), table_name='player')
    op.drop_table('player')
    op.drop_index(op.f('ix_obituary_szMd5'), table_name='obituary')
    op.drop_table('obituary')
    op.drop_index(op.f('ix_demo_szMd5'), table_name='demo')
    op.drop_table('demo')
    op.drop_index(op.f('ix_bulletevent_szMd5'), table_name='bulletevent')
    op.drop_table('bulletevent')
    # ### end Alembic commands ###
