"""empty message

Revision ID: 6fd39dfdf53f
Revises: 71cbf128d926
Create Date: 2020-06-30 07:04:47.253709

"""

# revision identifiers, used by Alembic.
revision = '6fd39dfdf53f'
down_revision = '71cbf128d926'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_demos', sa.Column('client_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('player_demos') as batch_op:
        batch_op.drop_column('client_num')
    # ### end Alembic commands ###
