"""empty message

Revision ID: 71cbf128d926
Revises: d2e31eefa2cb
Create Date: 2020-06-30 06:12:51.877519

"""

# revision identifiers, used by Alembic.
revision = '71cbf128d926'
down_revision = 'd2e31eefa2cb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nick', sa.String(length=8), nullable=True),
    sa.Column('country_iso', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_profiles'))
    )
    op.create_table('player_demos',
    sa.Column('player_profile_id', sa.Integer(), nullable=False),
    sa.Column('demo_player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(('demo_player_id',), ['player.dwSeq'], name=op.f('fk_player_demos_demo_player_id_player')),
    sa.ForeignKeyConstraint(('player_profile_id',), ['player_profiles.id'], name=op.f('fk_player_demos_player_profile_id_player_profiles')),
    sa.PrimaryKeyConstraint('player_profile_id', 'demo_player_id', name=op.f('pk_player_demos'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_demos')
    op.drop_table('player_profiles')
    # ### end Alembic commands ###
