"""empty message

Revision ID: 831471f4db93
Revises: e4800e6be8b1
Create Date: 2017-02-20 22:41:14.990682

"""

# revision identifiers, used by Alembic.
revision = '831471f4db93'
down_revision = 'e4800e6be8b1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gtv_match_id', sa.Integer(), nullable=True),
    sa.Column('client_num', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(),sa.ForeignKey('players.id'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    #op.create_foreign_key(None, 'renders', 'players', ['player_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'renders', type_='foreignkey')
    op.drop_table('match_players')
    ### end Alembic commands ###
