"""empty message

Revision ID: 83164addfe2d
Revises: 022302295875
Create Date: 2018-06-25 20:07:03.781654

"""

# revision identifiers, used by Alembic.
revision = '83164addfe2d'
down_revision = '022302295875'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_demos',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('demo_md5', sa.String(32), nullable=False),
    sa.ForeignKeyConstraint(['demo_md5'], ['demo.szMd5'], name=op.f('fk_match_demos_demo_md5_demo')),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_match_demos_match_id_matches')),
    sa.PrimaryKeyConstraint('match_id', 'demo_md5', name=op.f('pk_match_demos'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_demos')
    # ### end Alembic commands ###
