"""render match,player,map

Revision ID: a3b2622bc481
Revises: 45aa7927492c
Create Date: 2017-02-16 15:48:28.701191

"""

# revision identifiers, used by Alembic.
revision = 'a3b2622bc481'
down_revision = '45aa7927492c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('renders', sa.Column('gtv_match_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('renders', 'gtv_match_id')
    ### end Alembic commands ###
