"""empty message

Revision ID: b795470cf5b7
Revises: a3b2622bc481
Create Date: 2017-02-16 15:52:38.435587

"""

# revision identifiers, used by Alembic.
revision = 'b795470cf5b7'
down_revision = 'a3b2622bc481'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('renders', sa.Column('client_num', sa.Integer(), nullable=True))
    op.add_column('renders', sa.Column('map_number', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('renders', 'map_number')
    op.drop_column('renders', 'client_num')
    ### end Alembic commands ###
