"""empty message

Revision ID: e2e6df884138
Revises: 45aa7927492c
Create Date: 2017-02-17 03:51:26.191152

"""

# revision identifiers, used by Alembic.
revision = 'e2e6df884138'
down_revision = '45aa7927492c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('renders', sa.Column('client_num', sa.Integer(), nullable=True))
    op.add_column('renders', sa.Column('gtv_match_id', sa.Integer(), nullable=True))
    op.add_column('renders', sa.Column('map_number', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('renders', 'map_number')
    op.drop_column('renders', 'gtv_match_id')
    op.drop_column('renders', 'client_num')
    ### end Alembic commands ###
