"""empty message

Revision ID: e4800e6be8b1
Revises: b795470cf5b7
Create Date: 2017-02-18 12:25:44.257121

"""

# revision identifiers, used by Alembic.
revision = 'e4800e6be8b1'
down_revision = 'b795470cf5b7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=5), nullable=True),
    sa.Column('player_id', sa.Integer(),sa.ForeignKey('players.id'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    ### end Alembic commands ###
